remote_theme: just-the-docs/just-the-docs
search_enabled: true

logo: "/images/nfdi4health.png"
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


title:            Local Data Hub Documentation
